### ISSUE TITLE
A mistake of generate-data.m

### ISSUE THREAD

**Issue by zhanbingye** [burghoff/turbo-comb#1]
Vn = wn + exp(i*(p0 +ns.'.*pD ))*As;
this line is wrong，the prompt is Matrix dimensions must be consistent
so .*is wrong used 
I want to konw how to solve this problem.
thank you very much.

**Comment by burghoff** [comment]
This code only works in recent versions of Matlab that have [implicit expansion](https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/), which I believe was introduced in 2016b.
